version: '3.7'

services:
  fleetdb:
    depends_on:
      - jaeger
    environment:
      - FLEETDB_TRACING_ENABLED=true
      - FLEETDB_TRACING_ENVIRONMENT=dev-dockercompose
      - FLEETDB_TRACING_PROVIDER=jaeger
      - FLEETDB_TRACING_JAEGER_ENDPOINT=http://jaeger:14268/api/traces

  jaeger:
    image: jaegertracing/all-in-one:1.58.0
    ports:
      - "16686:16686" # The UI port
    networks:
      - hollow
