// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// BiosConfigComponent is an object representing the database table.
type BiosConfigComponent struct {
	ID                string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	FKBiosConfigSetID string    `boil:"fk_bios_config_set_id" json:"fk_bios_config_set_id" toml:"fk_bios_config_set_id" yaml:"fk_bios_config_set_id"`
	Name              string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Vendor            string    `boil:"vendor" json:"vendor" toml:"vendor" yaml:"vendor"`
	Model             string    `boil:"model" json:"model" toml:"model" yaml:"model"`
	CreatedAt         null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt         null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *biosConfigComponentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L biosConfigComponentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BiosConfigComponentColumns = struct {
	ID                string
	FKBiosConfigSetID string
	Name              string
	Vendor            string
	Model             string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	FKBiosConfigSetID: "fk_bios_config_set_id",
	Name:              "name",
	Vendor:            "vendor",
	Model:             "model",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var BiosConfigComponentTableColumns = struct {
	ID                string
	FKBiosConfigSetID string
	Name              string
	Vendor            string
	Model             string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "bios_config_components.id",
	FKBiosConfigSetID: "bios_config_components.fk_bios_config_set_id",
	Name:              "bios_config_components.name",
	Vendor:            "bios_config_components.vendor",
	Model:             "bios_config_components.model",
	CreatedAt:         "bios_config_components.created_at",
	UpdatedAt:         "bios_config_components.updated_at",
}

// Generated where

var BiosConfigComponentWhere = struct {
	ID                whereHelperstring
	FKBiosConfigSetID whereHelperstring
	Name              whereHelperstring
	Vendor            whereHelperstring
	Model             whereHelperstring
	CreatedAt         whereHelpernull_Time
	UpdatedAt         whereHelpernull_Time
}{
	ID:                whereHelperstring{field: "\"bios_config_components\".\"id\""},
	FKBiosConfigSetID: whereHelperstring{field: "\"bios_config_components\".\"fk_bios_config_set_id\""},
	Name:              whereHelperstring{field: "\"bios_config_components\".\"name\""},
	Vendor:            whereHelperstring{field: "\"bios_config_components\".\"vendor\""},
	Model:             whereHelperstring{field: "\"bios_config_components\".\"model\""},
	CreatedAt:         whereHelpernull_Time{field: "\"bios_config_components\".\"created_at\""},
	UpdatedAt:         whereHelpernull_Time{field: "\"bios_config_components\".\"updated_at\""},
}

// BiosConfigComponentRels is where relationship names are stored.
var BiosConfigComponentRels = struct {
	FKBiosConfigSet                         string
	FKBiosConfigComponentBiosConfigSettings string
}{
	FKBiosConfigSet:                         "FKBiosConfigSet",
	FKBiosConfigComponentBiosConfigSettings: "FKBiosConfigComponentBiosConfigSettings",
}

// biosConfigComponentR is where relationships are stored.
type biosConfigComponentR struct {
	FKBiosConfigSet                         *BiosConfigSet         `boil:"FKBiosConfigSet" json:"FKBiosConfigSet" toml:"FKBiosConfigSet" yaml:"FKBiosConfigSet"`
	FKBiosConfigComponentBiosConfigSettings BiosConfigSettingSlice `boil:"FKBiosConfigComponentBiosConfigSettings" json:"FKBiosConfigComponentBiosConfigSettings" toml:"FKBiosConfigComponentBiosConfigSettings" yaml:"FKBiosConfigComponentBiosConfigSettings"`
}

// NewStruct creates a new relationship struct
func (*biosConfigComponentR) NewStruct() *biosConfigComponentR {
	return &biosConfigComponentR{}
}

func (r *biosConfigComponentR) GetFKBiosConfigSet() *BiosConfigSet {
	if r == nil {
		return nil
	}
	return r.FKBiosConfigSet
}

func (r *biosConfigComponentR) GetFKBiosConfigComponentBiosConfigSettings() BiosConfigSettingSlice {
	if r == nil {
		return nil
	}
	return r.FKBiosConfigComponentBiosConfigSettings
}

// biosConfigComponentL is where Load methods for each relationship are stored.
type biosConfigComponentL struct{}

var (
	biosConfigComponentAllColumns            = []string{"id", "fk_bios_config_set_id", "name", "vendor", "model", "created_at", "updated_at"}
	biosConfigComponentColumnsWithoutDefault = []string{"fk_bios_config_set_id", "name", "vendor", "model"}
	biosConfigComponentColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	biosConfigComponentPrimaryKeyColumns     = []string{"id"}
	biosConfigComponentGeneratedColumns      = []string{}
)

type (
	// BiosConfigComponentSlice is an alias for a slice of pointers to BiosConfigComponent.
	// This should almost always be used instead of []BiosConfigComponent.
	BiosConfigComponentSlice []*BiosConfigComponent
	// BiosConfigComponentHook is the signature for custom BiosConfigComponent hook methods
	BiosConfigComponentHook func(context.Context, boil.ContextExecutor, *BiosConfigComponent) error

	biosConfigComponentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	biosConfigComponentType                 = reflect.TypeOf(&BiosConfigComponent{})
	biosConfigComponentMapping              = queries.MakeStructMapping(biosConfigComponentType)
	biosConfigComponentPrimaryKeyMapping, _ = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, biosConfigComponentPrimaryKeyColumns)
	biosConfigComponentInsertCacheMut       sync.RWMutex
	biosConfigComponentInsertCache          = make(map[string]insertCache)
	biosConfigComponentUpdateCacheMut       sync.RWMutex
	biosConfigComponentUpdateCache          = make(map[string]updateCache)
	biosConfigComponentUpsertCacheMut       sync.RWMutex
	biosConfigComponentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var biosConfigComponentAfterSelectHooks []BiosConfigComponentHook

var biosConfigComponentBeforeInsertHooks []BiosConfigComponentHook
var biosConfigComponentAfterInsertHooks []BiosConfigComponentHook

var biosConfigComponentBeforeUpdateHooks []BiosConfigComponentHook
var biosConfigComponentAfterUpdateHooks []BiosConfigComponentHook

var biosConfigComponentBeforeDeleteHooks []BiosConfigComponentHook
var biosConfigComponentAfterDeleteHooks []BiosConfigComponentHook

var biosConfigComponentBeforeUpsertHooks []BiosConfigComponentHook
var biosConfigComponentAfterUpsertHooks []BiosConfigComponentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BiosConfigComponent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BiosConfigComponent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BiosConfigComponent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BiosConfigComponent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BiosConfigComponent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BiosConfigComponent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BiosConfigComponent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BiosConfigComponent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BiosConfigComponent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range biosConfigComponentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBiosConfigComponentHook registers your hook function for all future operations.
func AddBiosConfigComponentHook(hookPoint boil.HookPoint, biosConfigComponentHook BiosConfigComponentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		biosConfigComponentAfterSelectHooks = append(biosConfigComponentAfterSelectHooks, biosConfigComponentHook)
	case boil.BeforeInsertHook:
		biosConfigComponentBeforeInsertHooks = append(biosConfigComponentBeforeInsertHooks, biosConfigComponentHook)
	case boil.AfterInsertHook:
		biosConfigComponentAfterInsertHooks = append(biosConfigComponentAfterInsertHooks, biosConfigComponentHook)
	case boil.BeforeUpdateHook:
		biosConfigComponentBeforeUpdateHooks = append(biosConfigComponentBeforeUpdateHooks, biosConfigComponentHook)
	case boil.AfterUpdateHook:
		biosConfigComponentAfterUpdateHooks = append(biosConfigComponentAfterUpdateHooks, biosConfigComponentHook)
	case boil.BeforeDeleteHook:
		biosConfigComponentBeforeDeleteHooks = append(biosConfigComponentBeforeDeleteHooks, biosConfigComponentHook)
	case boil.AfterDeleteHook:
		biosConfigComponentAfterDeleteHooks = append(biosConfigComponentAfterDeleteHooks, biosConfigComponentHook)
	case boil.BeforeUpsertHook:
		biosConfigComponentBeforeUpsertHooks = append(biosConfigComponentBeforeUpsertHooks, biosConfigComponentHook)
	case boil.AfterUpsertHook:
		biosConfigComponentAfterUpsertHooks = append(biosConfigComponentAfterUpsertHooks, biosConfigComponentHook)
	}
}

// One returns a single biosConfigComponent record from the query.
func (q biosConfigComponentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BiosConfigComponent, error) {
	o := &BiosConfigComponent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bios_config_components")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BiosConfigComponent records from the query.
func (q biosConfigComponentQuery) All(ctx context.Context, exec boil.ContextExecutor) (BiosConfigComponentSlice, error) {
	var o []*BiosConfigComponent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BiosConfigComponent slice")
	}

	if len(biosConfigComponentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BiosConfigComponent records in the query.
func (q biosConfigComponentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bios_config_components rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q biosConfigComponentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bios_config_components exists")
	}

	return count > 0, nil
}

// FKBiosConfigSet pointed to by the foreign key.
func (o *BiosConfigComponent) FKBiosConfigSet(mods ...qm.QueryMod) biosConfigSetQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FKBiosConfigSetID),
	}

	queryMods = append(queryMods, mods...)

	return BiosConfigSets(queryMods...)
}

// FKBiosConfigComponentBiosConfigSettings retrieves all the bios_config_setting's BiosConfigSettings with an executor via fk_bios_config_component_id column.
func (o *BiosConfigComponent) FKBiosConfigComponentBiosConfigSettings(mods ...qm.QueryMod) biosConfigSettingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"bios_config_settings\".\"fk_bios_config_component_id\"=?", o.ID),
	)

	return BiosConfigSettings(queryMods...)
}

// LoadFKBiosConfigSet allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (biosConfigComponentL) LoadFKBiosConfigSet(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBiosConfigComponent interface{}, mods queries.Applicator) error {
	var slice []*BiosConfigComponent
	var object *BiosConfigComponent

	if singular {
		var ok bool
		object, ok = maybeBiosConfigComponent.(*BiosConfigComponent)
		if !ok {
			object = new(BiosConfigComponent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBiosConfigComponent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBiosConfigComponent))
			}
		}
	} else {
		s, ok := maybeBiosConfigComponent.(*[]*BiosConfigComponent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBiosConfigComponent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBiosConfigComponent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &biosConfigComponentR{}
		}
		args = append(args, object.FKBiosConfigSetID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &biosConfigComponentR{}
			}

			for _, a := range args {
				if a == obj.FKBiosConfigSetID {
					continue Outer
				}
			}

			args = append(args, obj.FKBiosConfigSetID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`bios_config_sets`),
		qm.WhereIn(`bios_config_sets.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load BiosConfigSet")
	}

	var resultSlice []*BiosConfigSet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice BiosConfigSet")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for bios_config_sets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for bios_config_sets")
	}

	if len(biosConfigSetAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.FKBiosConfigSet = foreign
		if foreign.R == nil {
			foreign.R = &biosConfigSetR{}
		}
		foreign.R.FKBiosConfigSetBiosConfigComponents = append(foreign.R.FKBiosConfigSetBiosConfigComponents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FKBiosConfigSetID == foreign.ID {
				local.R.FKBiosConfigSet = foreign
				if foreign.R == nil {
					foreign.R = &biosConfigSetR{}
				}
				foreign.R.FKBiosConfigSetBiosConfigComponents = append(foreign.R.FKBiosConfigSetBiosConfigComponents, local)
				break
			}
		}
	}

	return nil
}

// LoadFKBiosConfigComponentBiosConfigSettings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (biosConfigComponentL) LoadFKBiosConfigComponentBiosConfigSettings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBiosConfigComponent interface{}, mods queries.Applicator) error {
	var slice []*BiosConfigComponent
	var object *BiosConfigComponent

	if singular {
		var ok bool
		object, ok = maybeBiosConfigComponent.(*BiosConfigComponent)
		if !ok {
			object = new(BiosConfigComponent)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBiosConfigComponent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBiosConfigComponent))
			}
		}
	} else {
		s, ok := maybeBiosConfigComponent.(*[]*BiosConfigComponent)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBiosConfigComponent)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBiosConfigComponent))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &biosConfigComponentR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &biosConfigComponentR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`bios_config_settings`),
		qm.WhereIn(`bios_config_settings.fk_bios_config_component_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load bios_config_settings")
	}

	var resultSlice []*BiosConfigSetting
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice bios_config_settings")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on bios_config_settings")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for bios_config_settings")
	}

	if len(biosConfigSettingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FKBiosConfigComponentBiosConfigSettings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &biosConfigSettingR{}
			}
			foreign.R.FKBiosConfigComponent = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FKBiosConfigComponentID {
				local.R.FKBiosConfigComponentBiosConfigSettings = append(local.R.FKBiosConfigComponentBiosConfigSettings, foreign)
				if foreign.R == nil {
					foreign.R = &biosConfigSettingR{}
				}
				foreign.R.FKBiosConfigComponent = local
				break
			}
		}
	}

	return nil
}

// SetFKBiosConfigSet of the biosConfigComponent to the related item.
// Sets o.R.FKBiosConfigSet to related.
// Adds o to related.R.FKBiosConfigSetBiosConfigComponents.
func (o *BiosConfigComponent) SetFKBiosConfigSet(ctx context.Context, exec boil.ContextExecutor, insert bool, related *BiosConfigSet) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bios_config_components\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"fk_bios_config_set_id"}),
		strmangle.WhereClause("\"", "\"", 2, biosConfigComponentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FKBiosConfigSetID = related.ID
	if o.R == nil {
		o.R = &biosConfigComponentR{
			FKBiosConfigSet: related,
		}
	} else {
		o.R.FKBiosConfigSet = related
	}

	if related.R == nil {
		related.R = &biosConfigSetR{
			FKBiosConfigSetBiosConfigComponents: BiosConfigComponentSlice{o},
		}
	} else {
		related.R.FKBiosConfigSetBiosConfigComponents = append(related.R.FKBiosConfigSetBiosConfigComponents, o)
	}

	return nil
}

// AddFKBiosConfigComponentBiosConfigSettings adds the given related objects to the existing relationships
// of the bios_config_component, optionally inserting them as new records.
// Appends related to o.R.FKBiosConfigComponentBiosConfigSettings.
// Sets related.R.FKBiosConfigComponent appropriately.
func (o *BiosConfigComponent) AddFKBiosConfigComponentBiosConfigSettings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*BiosConfigSetting) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FKBiosConfigComponentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"bios_config_settings\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"fk_bios_config_component_id"}),
				strmangle.WhereClause("\"", "\"", 2, biosConfigSettingPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FKBiosConfigComponentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &biosConfigComponentR{
			FKBiosConfigComponentBiosConfigSettings: related,
		}
	} else {
		o.R.FKBiosConfigComponentBiosConfigSettings = append(o.R.FKBiosConfigComponentBiosConfigSettings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &biosConfigSettingR{
				FKBiosConfigComponent: o,
			}
		} else {
			rel.R.FKBiosConfigComponent = o
		}
	}
	return nil
}

// BiosConfigComponents retrieves all the records using an executor.
func BiosConfigComponents(mods ...qm.QueryMod) biosConfigComponentQuery {
	mods = append(mods, qm.From("\"bios_config_components\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"bios_config_components\".*"})
	}

	return biosConfigComponentQuery{q}
}

// FindBiosConfigComponent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBiosConfigComponent(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*BiosConfigComponent, error) {
	biosConfigComponentObj := &BiosConfigComponent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"bios_config_components\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, biosConfigComponentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bios_config_components")
	}

	if err = biosConfigComponentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return biosConfigComponentObj, err
	}

	return biosConfigComponentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BiosConfigComponent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bios_config_components provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(biosConfigComponentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	biosConfigComponentInsertCacheMut.RLock()
	cache, cached := biosConfigComponentInsertCache[key]
	biosConfigComponentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			biosConfigComponentAllColumns,
			biosConfigComponentColumnsWithDefault,
			biosConfigComponentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"bios_config_components\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"bios_config_components\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bios_config_components")
	}

	if !cached {
		biosConfigComponentInsertCacheMut.Lock()
		biosConfigComponentInsertCache[key] = cache
		biosConfigComponentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BiosConfigComponent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BiosConfigComponent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	biosConfigComponentUpdateCacheMut.RLock()
	cache, cached := biosConfigComponentUpdateCache[key]
	biosConfigComponentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			biosConfigComponentAllColumns,
			biosConfigComponentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bios_config_components, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"bios_config_components\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, biosConfigComponentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, append(wl, biosConfigComponentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bios_config_components row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bios_config_components")
	}

	if !cached {
		biosConfigComponentUpdateCacheMut.Lock()
		biosConfigComponentUpdateCache[key] = cache
		biosConfigComponentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q biosConfigComponentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bios_config_components")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bios_config_components")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BiosConfigComponentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), biosConfigComponentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"bios_config_components\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, biosConfigComponentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in biosConfigComponent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all biosConfigComponent")
	}
	return rowsAff, nil
}

// Delete deletes a single BiosConfigComponent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BiosConfigComponent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BiosConfigComponent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), biosConfigComponentPrimaryKeyMapping)
	sql := "DELETE FROM \"bios_config_components\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bios_config_components")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bios_config_components")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q biosConfigComponentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no biosConfigComponentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bios_config_components")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bios_config_components")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BiosConfigComponentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(biosConfigComponentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), biosConfigComponentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"bios_config_components\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, biosConfigComponentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from biosConfigComponent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bios_config_components")
	}

	if len(biosConfigComponentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BiosConfigComponent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBiosConfigComponent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BiosConfigComponentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BiosConfigComponentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), biosConfigComponentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"bios_config_components\".* FROM \"bios_config_components\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, biosConfigComponentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BiosConfigComponentSlice")
	}

	*o = slice

	return nil
}

// BiosConfigComponentExists checks if the BiosConfigComponent row exists.
func BiosConfigComponentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"bios_config_components\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bios_config_components exists")
	}

	return exists, nil
}

// Exists checks if the BiosConfigComponent row exists.
func (o *BiosConfigComponent) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BiosConfigComponentExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BiosConfigComponent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bios_config_components provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(biosConfigComponentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	biosConfigComponentUpsertCacheMut.RLock()
	cache, cached := biosConfigComponentUpsertCache[key]
	biosConfigComponentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			biosConfigComponentAllColumns,
			biosConfigComponentColumnsWithDefault,
			biosConfigComponentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			biosConfigComponentAllColumns,
			biosConfigComponentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert bios_config_components, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(biosConfigComponentPrimaryKeyColumns))
			copy(conflict, biosConfigComponentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryCockroachDB(dialect, "\"bios_config_components\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(biosConfigComponentType, biosConfigComponentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		_, _ = fmt.Fprintln(boil.DebugWriter, cache.query)
		_, _ = fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // CockcorachDB doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert bios_config_components")
	}

	if !cached {
		biosConfigComponentUpsertCacheMut.Lock()
		biosConfigComponentUpsertCache[key] = cache
		biosConfigComponentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
