// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AocMacAddress              string
	Attributes                 string
	AttributesFirmwareSet      string
	BiosConfigComponents       string
	BiosConfigSets             string
	BiosConfigSettings         string
	BMCMacAddress              string
	BomInfo                    string
	ComponentFirmwareSet       string
	ComponentFirmwareSetMap    string
	ComponentFirmwareVersion   string
	EventHistory               string
	FirmwareSetValidationFacts string
	ServerComponentTypes       string
	ServerComponents           string
	ServerCredentialTypes      string
	ServerCredentials          string
	Servers                    string
	VersionedAttributes        string
}{
	AocMacAddress:              "aoc_mac_address",
	Attributes:                 "attributes",
	AttributesFirmwareSet:      "attributes_firmware_set",
	BiosConfigComponents:       "bios_config_components",
	BiosConfigSets:             "bios_config_sets",
	BiosConfigSettings:         "bios_config_settings",
	BMCMacAddress:              "bmc_mac_address",
	BomInfo:                    "bom_info",
	ComponentFirmwareSet:       "component_firmware_set",
	ComponentFirmwareSetMap:    "component_firmware_set_map",
	ComponentFirmwareVersion:   "component_firmware_version",
	EventHistory:               "event_history",
	FirmwareSetValidationFacts: "firmware_set_validation_facts",
	ServerComponentTypes:       "server_component_types",
	ServerComponents:           "server_components",
	ServerCredentialTypes:      "server_credential_types",
	ServerCredentials:          "server_credentials",
	Servers:                    "servers",
	VersionedAttributes:        "versioned_attributes",
}
